language: php

php:
   - 5.3
   - 5.5

env:
   global:
      - secure: "Alx64zOOxuE+ilARb7eXrx9KOAidntEnZpofCbgTjAYtO2pR9pG6A4N4snBhEna3XZsNSGbA7aVly8HAEezuOqN3BS0mr0LZ3ZT9gx0G/79pWjyzvel5jHjDLQZL/ci07L/3JTGje0rqFSK2CzsV1Ltz6nrdQh590hM6nJMMjB4="

before_script:
   - bundle install
   - composer self-update
   - sh -c "if $TRAVIS_SECURE_ENV_VARS; then composer config --global github-oauth.github.com $GITHUB_OAUTH_TOKEN; fi"
   - composer install

script:
   - bin/phpunit
   - bin/phpcs --standard=vendor/apnet/coding-standard/src/Apnet src
   - bin/phpcs --standard=vendor/apnet/coding-standard/src/Apnet app/src
