services:
    # Twig extension for README.md on /
    apnet.dev.twig_extension:
        class: Apnet\Dev\TwigExtension
        tags:
            - { name: twig.extension }

    apnet.assetic.importer.bootstrap_css:
        parent: assetic.importer_compass
        arguments:
            - %kernel.root_dir%/Resources/assets/config.rb
            - bootstrap
        tags:
            - { name: apnet.assetic.config_mapper, watcher: compass }
