services:
    # Twig extension for README.md on /
    apnet.dev.twig_extension:
        class: Apnet\Dev\TwigExtension
        tags:
            - { name: twig.extension }

    apnet.assetic.importer.jquery:
        parent: assetic.importer_path
        arguments:
            - %kernel.root_dir%/../vendor/apnet/jquery/app/Resources/assets/dist
            - jquery
        tags:
            - { name: apnet.assetic.config_mapper }

    apnet.importer.bootstrap_css:
        parent: assetic.importer_compass
        arguments:
            - %kernel.root_dir%/Resources/assets/config.rb
            - bootstrap
        tags:
            - { name: apnet.assetic.config_mapper, watcher: compass }

    apnet.importer.bootstrap_js:
        parent: assetic.importer_bootstrap_js
        arguments:
            - %kernel.root_dir%/Resources/assets/config.yml
            - bootstrap
        tags:
            - { name: apnet.assetic.config_mapper, watcher: bootstrap_js }
